- copy:
    dest: /etc/dcache/dcache.conf
    owner: dcache
    group: dcache
    mode: "0644"
    content: "dcache.layout=pool\n"
- template: 
    src: pool.conf.j2
    dest: /etc/dcache/layouts/pool.conf
    owner: dcache
    group: dcache
    mode: "0644"
- name: Restart dcache
  command: dcache restart
 
